# SPDX-License-Identifier: GPL-2.0-or-later
name: inkscape
adopt-info: inkscape
license: GPL-3.0
confinement: strict
base: core24
compression: lzo

plugs:
  dot-config-inkscape:
    interface: personal-files
    write: [ $HOME/.config/inkscape ]
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

slots:
  inkscape-dbus:
    interface: dbus
    bus: session
    name: org.inkscape.Inkscape

# commented out due to bug https://github.com/canonical/snapcraft/issues/4931
# will be added automatically by snapcraft anyway
# assumes: [ command-chain ]

parts:
  inkscape:
    plugin: cmake
    source: .
    cmake-generator: Ninja
    cmake-parameters:
      - '-DCMAKE_INSTALL_PREFIX='
    build-packages:
#       NOTE: Most dependencies are already provided by "extension: gnome" (see later).
      - cython3
      - libart-2.0-dev
      - libboost-all-dev
      - libcdr-dev
      - libdouble-conversion-dev
      - libgc-dev
      - libgsl-dev
      - libgtest-dev
      - libmagick++-dev
      - libpoppler-glib-dev
      - libpoppler-private-dev
      - libpotrace-dev
      - librevenge-dev
      - libreadline-dev
      - libspelling-1-dev
      - libvisio-dev
      - libwpg-dev
      - libxml-parser-perl
      - libxslt1-dev
      - ragel
    stage-packages:
#       NOTE: Most dependencies are already provided by "extension: gnome" (see later).
      - libboost-filesystem1.83.0
      - libcdr-0.1-1
      - libdouble-conversion3
      - libgc1
      - libgsl27
      - libgslcblas0
      - libmagick++-6.q16-9
      - libpoppler-glib8
      - libpotrace0
      - libproxy1v5
      - librevenge-0.0-0
      - libspelling-1-1
      - libvisio-0.1-1
      - libwpg-0.3-3
      - libxslt1.1
      - imagemagick
      - libimage-magick-perl
      - libwmf-bin
      - transfig
      - libsvg-perl
      - libxml-xql-perl
    prime:
      - -lib/inkscape/*.a
      - -*canberra*so* # We don't have sound permissions anyway
      - -usr/lib/*/gtk-2.0
    override-build: |
      sed -i.bak -e 's|Icon=${INKSCAPE_ICONPATH}|Icon=${SNAP}/share/inkscape/branding/inkscape.svg|g' $SNAPCRAFT_PART_SRC/org.inkscape.Inkscape.desktop.template
      craftctl default
      INKSCAPE_VERSION=`g++ -I${SNAPCRAFT_PART_SRC}/src ${SNAPCRAFT_PART_BUILD}/src/inkscape-version.cpp ${SNAPCRAFT_PROJECT_DIR}/snap/local/print-inkscape-version.cpp -o print-inkscape-version && ./print-inkscape-version`
      echo "Inkscape Version: ${INKSCAPE_VERSION}"
      craftctl set version="${INKSCAPE_VERSION}"
    override-prime: |
      craftctl default
      sed -i "s|_have.*$||" $SNAPCRAFT_PRIME/share/bash-completion/completions/inkscape
    parse-info: [ share/metainfo/org.inkscape.Inkscape.appdata.xml ]
    after: [python-deps] # Grab the network stuff first

  python-deps:
    plugin: python
    source: ./share/extensions
#   Unfortunately, snap only supports one pyproject.toml file.
#   It takes the dependencies from ./share/extensions/pyproject.toml.
#   The content of other pyproject.toml files is transferred here manually:
    python-packages:
#    the following dependencies are taken manually from share/extensions/other/inkman/pyproject.toml:
      - requests
      - appdirs
      - filelock
      - cachecontrol[filecache]
#     the following dependencies are taken manually from share/extensions/other/clipart/pyproject.toml:
      - beautifulsoup4
    stage-packages:
      - optipng
#     - pstoedit
#     - texlive-latex-base
  snap-helpers:
    plugin: dump
    source: snap/local/scripts

apps:
  inkscape:
    # NOTE: The gnome extension provides a lot of magic during build and runtime.
    # It modifies the behavior of the above "parts" section:
    # It sets environment variables, installs packages and provides many custom-
    # built versions of Gtk related libraries. Unfortunately, these libraries
    # are sometimes incompatible with the system provided APT packages.
    # In general, it is better to list as few packages as possible in
    # "build-packages" and "stage-packages" above, so that the versions provided
    # by the gnome extensions are used instead.
    extensions: [ gnome ]
    command: bin/inkscape
    command-chain: [ inkscape-variables, private-fontcache ]
    plugs:
      - cups # printing
      - dot-config-inkscape
      - raw-usb # plotter support
      - network # for extension manager
    slots:
      - inkscape-dbus
    desktop: share/applications/org.inkscape.Inkscape.desktop
    common-id: org.inkscape.Inkscape
    completer: share/bash-completion/completions/inkscape
  viewer:
    extensions: [ gnome ]
    command: bin/inkview
    command-chain: [ inkscape-variables, private-fontcache ]
    plugs:
      - dot-config-inkscape

hooks:
  configure:
    plugs:
      - desktop
